version: "2"
services:
  translator:
    build: ./translator/
    restart: unless-stopped
    volumes:
      - ./translator/src/:/home/pdf-translator/
    ports:
      - 8765:8765
    working_dir: /home/pdf-translator/
    command: python3 main.py
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
  bot:
    build: ./bot/
    restart: unless-stopped
    volumes:
      - ./bot/src/:/src
    working_dir: /src/
    links:
      - "translator"
    command: python3 run.py
    

    